###
GET http://localhost:3200/comments
Authorization: Bearer zxxxxx


### Parent Comment

POST http://localhost:3200/comments
Authorization: Bearer zxxxxx

Content-Type: application/json

{
    "text": "second comment",
    "userId": "1"
}


### Nested Comment

POST http://localhost:3200/comments
Content-Type: application/json

{

    "text": "I am a nested second comment",
    "parentId": "1",
    "userId": "1"
}





###
GET http://localhost:3200/comments?parentId=12

