###
GET http://localhost:3200/users


###Create
POST http://localhost:3200/users
Content-Type: application/json

{
    "id": "1",
    "name": "John Doe"
}

### GET
GET http://localhost:3200/users/1
Content-Type: application/json

{
    "name": "John Doe"
}

### UPDATE
PATCH http://localhost:3200/users/1
Content-Type: application/json

{
    "name": "John Doe"
}